### ISSUE TITLE
Add visual monitor

### ISSUE THREAD

**Issue by amitaibu** [Gizra-Shoov/hiro#1]
http://www.vidtur.com/attractions-in-vienna

**Comment by amitaibu** [comment]
@DavidKohav ^^

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/18901

**Comment by mldk-tech** [comment]
http://www.gfycat.com/RemorsefulGreenHorseshoebat

**Comment by amitaibu** [comment]
@DavidKohav can you please add here also just the regression image (i.e use the "download" button on shoov)

**Comment by mldk-tech** [comment]
@amitaibu 
![browserstack-chrome homepage 1 960px baseline](https://cloud.githubusercontent.com/assets/5812423/11019646/2580dcec-860a-11e5-8b57-f634af492de1.png)

**Comment by amitaibu** [comment]
Thanks.
